---
- name: Install it
  community.general.snap:
    name: helm
    # classic confinement per Helm install recommendation
    classic: true
    channel: stable
    state: present

# TODO **securely** config ~/.config/helm file(s)
- name: Add provider configurations
  debug:
    msg: TODO config ~/.config/helm file(s), possibly in cloud-spec role(s)
