---
# Primarily for stripping packages and related apt cleanup so that the distro
# upgrade does not get tripped up by apt cruft.
#
# TODO After all local boxes are switched to Snaps, zap all save
# epson_scanner_remove and dist_upgrade.

- name: Play to prep for a distribution upgrade
  hosts: localhost
  roles:
    - vscode_remove
    - kubernetes_remove
    - matrix_remove
    - terraform_remove
    - helm_remove
    - epson_scanner_remove
    # should always come last:
    - dist_upgrade
