---
# Get ready for a distribution upgrade, but don't do the actual upgrade. It
# is still safer to do the actual upgrade manually from a terminal shell
# at this point.
- hosts: localhost
  roles:
    - vscode-remove
    - kubernetes-remove
    - matrix-remove
    - terraform-remove
    - helm-remove
    - dist-upgrade
