---
d_repo_base_url: https://github.com/ldc-developers/ldc/releases/download
d_version: 1.37.0
d_archive_checksum: sha256:55524bf320fcc7ed453c29a07e9a98a1716f278dbab7ba4c156dc2719b4671df
d_binaries:
  - ddemangle
  - dub
  - dustmite
  - ldc2
  - ldc-build-runtime
  - ldc-profdata
  - ldc-prune-cache
  - ldmd2
  - rdmd
  - reggae
d_user_home_subdir: ldc2-{{ d_version }}
d_user_home_dir: "{{ end_user_home }}/.local/bin/{{ d_user_home_subdir }}"
