---
extensions:
  - hashicorp.terraform
  - hbenl.vscode-test-explorer
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode.test-adapter-converter
  - redhat.ansible
  - redhat.vscode-yaml
  - webfreak.code-d
