---
- name: Add apt key
  apt_key:
    url: "{{ msoft_package_repo_base_url }}/keys/microsoft.asc"
    state: present

- name: Add apt repository
  apt_repository:
    repo: "deb {{ msoft_package_repo_base_url }}/repos/code stable main"
    filename: vscode
    state: present

- name: Install it
  apt:
    name: code
    state: present

- name: Sync user settings
  template:
    src: settings.json.j2
    dest: "{{ end_user_home }}/.config/Code/User/settings.json"
    owner: "{{ end_user }}"
    group: "{{ end_group }}"
    mode: 0644

#TODO sync plugins + settings if possible
