---
# TODO add id for change check + sanity check
- block:
  - name: Add apt key
    ansible.builtin.apt_key:
      url: "{{ msoft_package_repo_base_url }}/keys/microsoft.asc"
      # Recommended per MSoft over default /etc/apt/trusted.gpg.d/*.gpg
      keyring: "{{ microsoft_keyring }}"
      state: present

  - name: Add apt repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64,arm64,armhf signed-by={{ microsoft_keyring }}] {{ msoft_package_repo_base_url }}/repos/code stable main
      filename: vscode
      state: present
  vars:
    microsoft_keyring: /etc/apt/keyrings/packages.microsoft.gpg

- name: Install it
  ansible.builtin.apt:
    name: code
    state: present

- name: Install extensions
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
    creates: "{{ end_user_home }}/.vscode/extensions/{{ item }}*"
  loop: "{{ extensions }}"
  become: true
  become_user: "{{ end_user }}"

- name: Sync user settings
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ end_user_home }}/.config/Code/User/settings.json"
    owner: "{{ end_user }}"
    group: "{{ end_group }}"
    mode: 0644
