---
- name: Install it
  community.general.snap:
    name: code
    # classic confinement per VScode install recommendation
    classic: true
    channel: stable
    state: present

- name: Install extensions
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
    creates: "{{ end_user_home }}/.vscode/extensions/{{ item }}*"
  loop: "{{ extensions }}"
  become: true
  become_user: "{{ end_user }}"

- name: Sync user settings
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ end_user_home }}/.config/Code/User/settings.json"
    owner: "{{ end_user }}"
    group: "{{ end_group }}"
    mode: 0644
