---
#TODO Remove and/or switch, possibly
- name: Install Mirage
  apt:
    name: matrix-mirage
    state: present

#TODO If we really like Mirage, zap this
- name: Warn this Matrix client is perhaps temporary
  debug:
    msg: >
      NOTE: Thunderbird 102+ has an integrated Matrix client, and
      should be available soon in Debian and Ubuntu repos. Should that
      client suffice, or if Mirage otherwise does not work out, this
      playbook will need updating.
