---
# Backup-related utils

- name: Handy backup media filesystem create config
  ansible.builtin.blockinfile:
    path: /etc/mke2fs.conf
    block: |
      # like ext4 but no journaling
      ext4_backup = {
          features = ^has_journal,extent,huge_file,flex_bg,metadata_csum,64bit,dir_nlink,extra_isize
      }
    insertbefore: "ext4 ="
    marker: "# {mark} ANSIBLE MANAGED BLOCK - MKE2FS"
    state: present

- name: Install gocryptfs
  ansible.builtin.apt:
    name: gocryptfs
    state: present

- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present

# My backup scripts are in Groovy
- name: Install groovy
  ansible.builtin.apt:
    name: groovy
    state: present

- name: Look for existing gocryptfs config
  ansible.builtin.find:
    paths: "{{ backup_dirs }}"
    patterns: .gocryptfs.reverse.conf
    hidden: true
  register: backup_dirs_crypt_configs
  tags:
    - idempotency_check

# TODO generate ssh keys for easier access

# TODO create remote /etc, /home, /var, /root dirs?

# TODO Don't just warn of this, use gocryptfs with a _single_ password to init
- name: Warn of nonconfigured backed up dirs
  ansible.builtin.debug:
    msg: |
      At least one of {{ backup_dirs }} is not configured for gocryptfs reverse
      mounts. Create temporary directories for each, then
      `gocryptfs --init --aessiv` each of them using the same password, then
      copy the resulting `gocryptfs.conf` at the root of each over to the
      corresponding backup directory _renaming the files
      `.gocryptfs.reverse.conf`.
  when: backup_dirs_crypt_configs.matched < (backup_dirs | length)
