---
- name: Install ldc (actually ldc2)
  ansible.builtin.apt:
    name:
      - ldc
      - dub
    state: present

# The old steps used to grab binaries from GitHub and install them in $HOME.
# Warn of these old installs but don't do anything with them.
- name: Check for user installations
  ansible.builtin.find:
    paths: "{{ end_user_home }}/.local/bin"
    patterns: 'ldc2-*'
    file_type: directory
  register: other_user_binaries

- name: Warn of user installations
  when: other_user_binaries.matched > 0
  ansible.builtin.debug:
    msg: >
      WARNING: Other user installations detected. You may wish to remove them
      manually: {{ other_user_binaries | json_query('files[*].path') }}
