---
# Get ready for a distribution upgrade, but don't do the actual upgrade (yet).
# Remember that ansible_distribution_version is the *current* version, so we
# expact a tasks file named something like debian-11.yml.
- ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
