---
- name: Install it
  community.general.snap:
    name: kubectl
    # classic confinement per k8s install recommendation
    classic: true
    channel: stable
    state: present

- name: Create a kubeconfigs dir if necessary
  ansible.builtin.file:
    path: "{{ end_user_home }}/.kube/configs"
    state: directory
    owner: "{{ end_user }}"
    group: "{{ end_group }}"
    mode: 0775
  register: kubeconfigs_dir

- name: Find user kubeconfigs
  ansible.builtin.find:
    paths: "{{ kubeconfigs_dir.path }}"
    patterns:
      - '*.yml'
      - '*.yaml'
  register: kubeconfigs
  tags:
    - idempotency_check

- name: Clear KUBECONFIG variable in bash startup
  ansible.builtin.blockinfile:
    path: "{{ end_user_home }}/.bashrc"
    block: export KUBECONFIG=$KUBECONFIG
    marker: "# {mark} ANSIBLE MANAGED BLOCK - KUBECONFIG"
    state: present
  when: kubeconfigs.matched == 0

- name: Set KUBECONFIG variable in bash startup
  ansible.builtin.blockinfile:
    path: "{{ end_user_home }}/.bashrc"
    block: export KUBECONFIG=$KUBECONFIG:{{ kubeconfigs.files | map(attribute='path') | join(':') }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - KUBECONFIG"
    state: present
  when: kubeconfigs.matched > 0
