---
- name: Add apt key
  apt_key:
    url: "{{ google_cloud_package_repo_base_url }}/apt/doc/apt-key.gpg"
    #Recommended per k8s over default /etc/apt/trusted.gpg.d/*.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Add apt repository
  apt_repository:
    #See note above about nonstandard keyfile location
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] {{ kubernetes_package_repo_base_url }}/ kubernetes-xenial main"
    filename: kubernetes
    state: present

- name: Install it
  apt:
    name: kubectl
    state: present

- name: Set KUBECONFIG variable in bash startup
  blockinfile:
    path: "{{ end_user_home }}/.bashrc"
    block: export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config:$HOME/.kube/configs/learn-to-k8s-kubeconfig.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - KUBECONFIG"
    state: present

#TODO **securely** add ~/.kube/configs/*.yaml configs
- name: Add cluster configurations
  debug:
    msg: TODO add ~/.kube/configs/*.yaml configs
