---
- name: Install Podman
  ansible.builtin.apt:
    name: podman
    state: present

- name: Install Buildah
  ansible.builtin.apt:
    name: buildah
    state: present

- name: Install Skopeo
  ansible.builtin.apt:
    name: skopeo
    state: present

- name: Install Podman Compose
  ansible.builtin.apt:
    name: podman-compose
    state: present

# See https://github.com/microsoft/vscode/issues/232863 and
# https://github.com/containers/storage/blob/v1.51.0/docs/containers-storage.conf.5.md#storage-table
- name: Pin rootless container storage to $HOME
  ansible.builtin.copy:
    src: storage.conf
    dest: "{{ end_user_home }}/.config/containers/"
    owner: "{{ end_user }}"
    group: "{{ end_group }}"
    mode: "0644"
