---
- name: Install Podman
  ansible.builtin.apt:
    name: podman
    state: present

- name: Install Buildah
  ansible.builtin.apt:
    name: buildah
    state: present

- name: Install Skopeo
  ansible.builtin.apt:
    name: skopeo
    state: present
