---
- name: Install Podman
  apt:
    name: podman
    state: present

- name: Install Buildah
  apt:
    name: buildah
    state: present

- name: Install Skopeo
  apt:
    name: skopeo
    state: present
