---
- name: Install it
  community.general.snap:
    name: terraform
    # classic confinement per Snap listing install recommendation
    classic: true
    channel: stable
    state: present

# TODO **securely** add ~/terraform/*.tf provider files
- name: Add configuration
  debug:
    msg: TODO add ~/terraform/*.tf provider files, probably in cloud-spec role(s)
