---
# Naturally we can't bootstrap and install Ansible itself, but we want
# some other goodies and can configure it.

- name: Install linter, XML shim
  ansible.builtin.apt:
    name:
      - ansible-lint
      - python3-lxml
    state: present
