---
# Remove the package--don't purge--first
- name: Remove it, preserving config
  ansible.builtin.apt:
    name: element-desktop
    state: absent
    purge: false

- name: Disable vendor repo
  vars:
    repos_dir: /etc/apt/sources.list.d
    repo: element-io.list
  block:
    - name: Disable apt repository
      ansible.builtin.command:
        chdir: "{{ repos_dir }}"
        argv:
          - mv
          - --force
          - "{{ repo }}"
          - "{{ repo }}.bak"
        removes: "{{ repos_dir }}/{{ repo }}"
