---
# Remove the package
- name: Remove it, preserving config
  ansible.builtin.apt:
    name: epsonscan2
    state: absent
    purge: false

# There is no apt repo for this. The deb was downloaded from Epson and
# installed directly.
